[package]
name = "eikthyrnir-temp"
version = "0.1.0"
authors = ["SitiSchu <admin@sitischu.com>"]
edition = "2018"

[dependencies]
eikthyrnir = {path = "../eikthyrnir"}
clap = "3.0.0-beta.2"
walkdir = "2.3"
regex = "1.4"
