[package]
name = "eikthyrnir"
version = "0.1.0"
authors = ["SitiSchu <admin@sitischu.com>"]
edition = "2018"
description = "Random utilities stuffed into a single binary"

[[bin]]
path = "src/main.rs"
name = "e"

[dependencies]
colored = "1.9"
clap = "2.33"
