[package]
name = "eikthyrnir-web"
version = "0.1.0"
authors = ["SitiSchu <admin@sitischu.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
git2 = "0.12"
regex = "1.3"
open = "1.3"
eikthyrnir = {path = "../eikthyrnir"}
