[package]
name = "eikthyrnir-chaotica"
version = "0.2.0"
authors = ["SitiSchu <admin@sitischu.com>"]
edition = "2018"

[dependencies]
eikthyrnir = { path = "../eikthyrnir" }
clap = { version = "4.1", features = ["derive"] }
anyhow = "1.0"
quick-xml = "0.18.1"
