[package]
name = "eikthyrnir-open"
version = "0.1.0"
authors = ["SitiSchu <admin@sitischu.com>"]
edition = "2018"

[dependencies]
eikthyrnir = {path = "../eikthyrnir"}
clap = { version = "4.1", features = ["derive"] }
anyhow = "1.0"
open = "1.3"
